# Site
repository: Git repository where your resume will be hosted, only required if you are hosting on GitHub (eg. sproogen/modern-resume-theme)
# favicon: Directory of your favicon (eg. images/favicon.ico)(optional)

# Content configuration version
version: 2

# Personal info
name: Suleman Qaiser
title: Software Engineer (AWS Certified Developer)
# Dark Mode (true/false/never)
darkmode: false

# Social links
# twitter_username: jekyllrb
github_username: sulemanqaiser97
stackoverflow_username: "20874584"
linkedin_username: sulemanqaiser97

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/profile.png
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Suleman Qaiser. I am a software engineer with 3 years of industry experience in backend development using Node.js, JavaScript,TypeScript, and .NET Core as well as MERN stack. I have expertise in building and maintaining REST APIs,microservices, and serverless architectures using AWS services, as well as implementing continuous integration and delivery pipelines. I am skilled in troubleshooting and debugging complex issues and follow best coding practices such aswriting clean and well-documented code. I have experience optimizing the performance of applications through techniques including caching, load balancing, scaling, query optimization and database indexing.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Tintash
        sub_title: Software Engineer - Serverless
        caption: March 2022 - Continue
        description: | # this will include new lines to allow paragraphs


          * MyWordPal Project
          * Led the discovery phase by conducting client interviews and requirements analysis, ensuring project objectives aligned with client expectations and laying the foundation for a successful project.
          * Devised and implemented a high-performance backend architecture using NestJS and RDS PostgreSQL database, optimizing data storage and retrieval processes, and supporting seamless user experience.
          * Deployed the application on AWS Elastic Beanstalk, leveraging its scalability and manageability, and configured CI/CD pipelines to automate build, test, and deployment processes, resulting in increased efficiency and reduced time-to-market.
          * Fostered effective communication and collaboration between development, design, and product teams, ensuring timely project delivery and high-quality outputs.

          * CourseKey Project
          * Designed and implemented serverless solutions using AWS Lambda and API Gateway, improving scalability and availability. 
          * Designed state machines in AWS Step Functions to orchestrate Lambda functions for efficient, reliable data synchronization between systems, improving performance. 
          * Utilized advanced utility types and parallel processing in TypeScript to improve the efficiency of the synchronization process between different systems. 
          * Utilized Infrastructure as Code (IaC) to write and deploy Lambda functions through API Gateway, streamlining the development process and increasing efficiency. 
          * Implemented comprehensive unit tests using popular testing frameworks such as Jest and Mocha, utilizing TypeScript's strong type checking to ensure test reliability and contributed to increased code coverage and product quality.

          -Technologies: Lambda, Step Functions, Serverless Framework, NodeJS, Typescript, Javascript, MySQL, Sequelize
      - layout: left
        title: CureMD
        sub_title: Software Engineer
        caption: August 2020 - March 2022
        description: | # this will include new lines to allow paragraphs
          * Applied agile development methodologies and collaborated with the product management team to deliver new features and functionality, including translating business requirements into technical solutions and contributing to design and implementation efforts. 
          * Refactored the lab order service to an event-driven architecture and implemented secure RESTful APIs, improving communication efficiency, system reliability, and scalability. 
          * Designed schemas for Lab Codes in the central code repository using Elasticsearch to improve the performance and maintainability of the order placement process. 
          * Improved database query performance through indexing and optimized query structures, reducing data retrieval time and improving system performance. 
          * Developed components as an independent module for reusability across the application in Angular with TypeScript and implemented RXJS (reactive extension) for using Observable sequences to allow async data streams.

          -Technologies: Amazon Web Services (AWS) · MySQL · MongoDB · Object-Relational Mapping (ORM) · JavaScript · Angular Material · Angular · .NET Core · Reactive Programming · TypeScript, Elastic Search
      - layout: left
        title: Remote Work
        sub_title: Software Engineer
        caption: June 2019 - July 2020
        description: | # this will include new lines to allow paragraphs
          * Worked as a full-stack Web Developer. I developed end-to-end web applications using the MEAN stack, including the creation of server-side logic, database design and management, and front-end development.
      - layout: left
        title: LUMS
        sub_title: Research Assistant
        caption: Aug 2018 - Dec 2018
        description: | # this will include new lines to allow paragraphs
          * Examined the impact of different Circumvention mechanisms on the online advertising system and researched how anonymity can be preserved while enhancing the relevance of ads.

  - title: Projects # Title for the section
    layout: list # Type of content section (list/text)
    content:
      - layout: top-middle
        title: Optimal Scheduling Solutions for EVs Charging
        description: |
          Worked on devising an Optimal Scheduling Solutions for EVs Charging to reduce Grid stress and
          avoid blackouts by analyzing the trends and peak hours in Electric Load datasets provided by LESCO.
      - layout: top-middle
        title: BitTorrent and MapReduce Engine
        description: |
          Implemented BitTorrent and MapReduce Engine to share files by dividing them into reasonable
          chunks by means of peer-to-peer file sharing (P2P) protocol and processing large data sets in
          parallel across using map and reduce process respectively.
      - layout: top-middle
        title: Modern Operating Systems Components
        description: |
          Implemented the key components of modern operating systems (thread management,
          multiprogramming, and file systems) in NachOS on a MIPS emulator
      - layout: top-middle
        title: Web Platform for NGOs
        description: |
          Developed a Web platform named Internee using MERN stack framework for NGOs to assist
          them in locating Volunteers for their events
      - layout: top-middle
        title: Parallel data processing
        description: |
          Used U.S. Census Bureau data to answer real world questions, for swift data manipulation Golang was
          used as it provided framework for effective parallelism; the project was 70% time efficient than
          sequential python script.

  - title: Education
    layout: list
    content:
      - layout: top-left
        title: Lahore University of Management Sciences
        sub_title: BS Computer Science
        caption: 2015 - 2019
        #   quote: >
        description: | # this will include new lines to allow paragraphs
          Relevant Courses:
           - Advanced Programming
           - Network Security
           - Topics in Internet Research
           - Deep Learning
           - Principles and Techniques of Data Science
           - Operating Systems
           - Databases

  - title: TECHNICAL SKILLS
    layout: list
    content:
      - layout: top-left
        title: AWS Services
        description: |
          EC2, S3, Lambda, RDS, DynamoDB, API Gateway, SQS, SNS, ECS, EKS, Fargate, CloudWatch,
          CloudTrail, IAM, CodeBuild, CodeDeploy, CloudFormation, SAM
      - layout: top-left
        title: Languages
        description: |
          Python, Django, C/C++, Haskell, JavaScript, Golang, NodeJS, React, SQL, MongoDB, Angular, Typescript

# Footer
footer_show_references: false
# references_title: References on request (Override references text)

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag

exclude:
  [
    "Gemfile",
    "Gemfile.lock",
    "node_modules",
    "vendor/bundle/",
    "vendor/cache/",
    "vendor/gems/",
    "vendor/ruby/",
    "lib/",
    "scripts/",
    "docker-compose.yml",
  ]
